### ISSUE TITLE
[OmniBridge]: validate `native_fee_recipient`

### ISSUE THREAD

**Issue by karim-en** [Near-One/omni-bridge#50]
The chain kind of  `native_fee_recipient` should be equal to the `message.get_origin_chain()`
https://github.com/Near-One/omni-bridge/blob/1b88b4ee0df12e2f3007d4f2285e45b654c73b20/near/nep141-locker/src/lib.rs#L590-L591

**Comment by kiseln** [comment]
@karim-en not relevant anymore?
